export const MOCK_TESTS = [
  {
    id: 1,
    title: 'TOEIC Practice 1',
    slug: 'toeic-practice-1',
    duration: 40,
    participants: 213045,
    comments: 463,
    parts: 4,
    questions: 40,
    category: 'Toeic',
    skills: ['Listening', 'Reading'],
    totalQuestions: 200,
    completions: 1234,
    averageScore: '650/990',
  },
  {
    id: 2,
    title: 'TOEIC Practice 2',
    slug: 'toeic-practice-2',
    duration: 40,
    participants: 110904,
    comments: 205,
    parts: 4,
    questions: 40,
    category: 'Toeic',
    skills: ['Listening', 'Reading'],
    totalQuestions: 200,
    completions: 1234,
    averageScore: '650/990',
  },
  {
    id: 3,
    title: 'TOEIC Practice 3',
    slug: 'toeic-practice-3',
    duration: 40,
    participants: 77370,
    comments: 220,
    parts: 4,
    questions: 40,
    category: 'Toeic',
    skills: ['Listening', 'Reading'],
    totalQuestions: 200,
    completions: 1234,
    averageScore: '650/990',
  },
  {
    id: 4,
    title: 'TOEIC Practice 4',
    slug: 'toeic-practice-4',
    duration: 40,
    participants: 63300,
    comments: 101,
    parts: 4,
    questions: 40,
    category: 'Toeic',
    skills: ['Listening', 'Reading'],
    totalQuestions: 200,
    completions: 1234,
    averageScore: '650/990',
  },
  {
    id: 5,
    title: 'TOEIC Practice 5',
    slug: 'toeic-practice-5',
    duration: 40,
    participants: 57564,
    comments: 147,
    parts: 4,
    questions: 40,
    category: 'Toeic',
    skills: ['Listening', 'Reading'],
    totalQuestions: 200,
    completions: 1234,
    averageScore: '650/990',
  },
  {
    id: 6,
    title: 'TOEIC Practice 6',
    slug: 'toeic-practice-6',
    duration: 40,
    participants: 53013,
    comments: 114,
    parts: 4,
    questions: 40,
    category: 'Toeic',
    skills: ['Listening', 'Reading'],
    totalQuestions: 200,
    completions: 1234,
    averageScore: '650/990',
  },
  {
    id: 7,
    title: 'TOEIC Practice 7',
    slug: 'toeic-practice-7',
    duration: 40,
    participants: 48714,
    comments: 99,
    parts: 4,
    questions: 40,
    category: 'Toeic',
    skills: ['Listening', 'Reading'],
    totalQuestions: 200,
    completions: 1234,
    averageScore: '650/990',
  },
  {
    id: 8,
    title: 'TOEIC Practice 8',
    slug: 'toeic-practice-8',
    duration: 40,
    participants: 47019,
    comments: 79,
    parts: 4,
    questions: 40,
    category: 'Toeic',
    skills: ['Listening', 'Reading'],
    totalQuestions: 200,
    completions: 1234,
    averageScore: '650/990',
  },
  {
    id: 9,
    title: 'IELTS Writing Task 1',
    slug: 'ielts-writing-task-1',
    duration: 60,
    participants: 35420,
    comments: 156,
    parts: 2,
    questions: 25,
    category: 'IELTS',
    skills: ['Writing'],
    totalQuestions: 200,
    completions: 1234,
    averageScore: '650/990',
  },
  {
    id: 10,
    title: 'IELTS Speaking Practice',
    slug: 'ielts-speaking-practice',
    duration: 30,
    participants: 28900,
    comments: 89,
    parts: 3,
    questions: 15,
    category: 'IELTS',
    skills: ['Speaking'],
    totalQuestions: 200,
    completions: 1234,
    averageScore: '650/990',
  },
  {
    id: 11,
    title: 'Grammar Foundation',
    slug: 'grammar-foundation',
    duration: 45,
    participants: 45600,
    comments: 234,
    parts: 5,
    questions: 50,
    category: 'Grammar',
    skills: ['Grammar'],
    totalQuestions: 200,
    completions: 1234,
    averageScore: '650/990',
  },
  {
    id: 12,
    title: 'Vocabulary Builder',
    slug: 'vocabulary-builder',
    duration: 25,
    participants: 67800,
    comments: 178,
    parts: 3,
    questions: 30,
    category: 'Vocabulary',
    skills: ['Vocabulary'],
    totalQuestions: 200,
    completions: 1234,
    averageScore: '650/990',
  },
];

export const PARTS = [
  { id: 1, name: 'Part 1: Photographs', type: 'Listening', questions: 6, duration: 10 },
  { id: 2, name: 'Part 2: Question-Response', type: 'Listening', questions: 25, duration: 25 },
  { id: 3, name: 'Part 3: Conversations', type: 'Listening', questions: 39, duration: 39 },
  { id: 4, name: 'Part 4: Talks', type: 'Listening', questions: 30, duration: 30 },
  { id: 5, name: 'Part 5: Incomplete Sentences', type: 'Reading', questions: 30, duration: 20 },
  { id: 6, name: 'Part 6: Text Completion', type: 'Reading', questions: 16, duration: 15 },
  { id: 7, name: 'Part 7: Reading Comprehension', type: 'Reading', questions: 54, duration: 75 },
];

export const SAMPLE_ANSWERS = [
  {
    question: 1,
    answer: 'A',
    explanation:
      'Trong hình ảnh, một người phụ nữ đang sử dụng máy tính. Đáp án A "She is working on a computer" là chính xác.',
  },
  {
    question: 2,
    answer: 'C',
    explanation: 'Câu hỏi về thời gian. Đáp án C "At 3 o\'clock" phù hợp nhất với ngữ cảnh.',
  },
  {
    question: 3,
    answer: 'B',
    explanation: 'Đây là câu hỏi về địa điểm. Đáp án B "In the conference room" là đúng.',
  },
];

export const COMMENTS = [
  {
    id: 1,
    user: 'Toàn đẹp trai',
    avatar: '👨‍💼',
    rating: 5,
    date: '2024-01-20',
    comment:
      'Đề thi rất hay, câu hỏi đa dạng và sát với đề thi thật. Phần giải thích chi tiết giúp mình hiểu rõ hơn.',
  },
  {
    id: 2,
    user: 'Toàn DZ',
    avatar: '👩‍🎓',
    rating: 4,
    date: '2024-01-18',
    comment:
      'Nội dung tốt nhưng audio ở Part 3 hơi nhanh. Nhìn chung vẫn rất hữu ích cho việc ôn tập.',
  },
  {
    id: 3,
    user: 'Toàn Hec cơ',
    avatar: '👨‍🎓',
    rating: 5,
    date: '2024-01-15',
    comment: 'Excellent! Đề thi này giúp mình cải thiện được 50 điểm. Recommend cho mọi người.',
  },
];
