import {
  Search,
  Volume2,
  Copy,
  Check,
  Edit2,
  Save,
  X,
  BookOpen,
  Zap,
  BarChart3,
  Gamepad2,
} from 'lucide-react';

export const MOCK_INITIAL_COLLECTION = {
  id: '1',
  name: 'Business Vocabulary',
  description: 'Từ vựng về kinh doanh và tài chính',
  vocabularies: [
    {
      id: '1',
      word: 'Accumulate',
      phonetic: '/əˈkjuːmjəleɪt/',
      partOfSpeech: 'verb',
      meaning: 'Tích lũy, tập hợp',
      example: 'The company accumulated wealth over decades.',
      synonyms: ['gather', 'collect', 'amass'],
      category: 'Business',
    },
    {
      id: '2',
      word: 'Advocate',
      phonetic: '/ˈædvəkət/',
      partOfSpeech: 'noun, verb',
      meaning: 'Người ủng hộ, bảo chữa; ủng hộ',
      example: 'She advocates for environmental protection.',
      synonyms: ['supporter', 'champion', 'promote'],
      category: 'General',
    },
    {
      id: '3',
      word: 'Ambiguous',
      phonetic: '/æmˈbɪɡjuəs/',
      partOfSpeech: 'adjective',
      meaning: 'Mơ hồ, không rõ ràng',
      example: 'His ambiguous response left everyone confused.',
      synonyms: ['unclear', 'vague', 'uncertain'],
      category: 'General',
    },
    {
      id: '4',
      word: 'Benevolent',
      phonetic: '/bəˈnevələnt/',
      partOfSpeech: 'adjective',
      meaning: 'Nhân từ, tốt bụng',
      example: 'The benevolent organization donated to charity.',
      synonyms: ['kind', 'generous', 'compassionate'],
      category: 'General',
    },
    {
      id: '5',
      word: 'Crucial',
      phonetic: '/ˈkruːʃəl/',
      partOfSpeech: 'adjective',
      meaning: 'Quan trọng, then chốt',
      example: 'This decision is crucial for our success.',
      synonyms: ['critical', 'essential', 'vital'],
      category: 'Business',
    },
    {
      id: '6',
      word: 'Diligent',
      phonetic: '/ˈdɪlɪdʒənt/',
      partOfSpeech: 'adjective',
      meaning: 'Chăm chỉ, siêng năng',
      example: 'He is a diligent student who studies every day.',
      synonyms: ['hardworking', 'industrious', 'persistent'],
      category: 'General',
    },
    {
      id: '7',
      word: 'Emerge',
      phonetic: '/ɪˈmɜːdʒ/',
      partOfSpeech: 'verb',
      meaning: 'Xuất hiện, nổi lên',
      example: 'New opportunities will emerge from the crisis.',
      synonyms: ['appear', 'arise', 'surface'],
      category: 'Business',
    },
    {
      id: '8',
      word: 'Facilitate',
      phonetic: '/fəˈsɪlɪteɪt/',
      partOfSpeech: 'verb',
      meaning: 'Tạo điều kiện, giúp cho',
      example: 'The software facilitates communication between teams.',
      synonyms: ['ease', 'assist', 'enable'],
      category: 'Business',
    },
    {
      id: '9',
      word: 'Gratify',
      phonetic: '/ˈɡrætɪfaɪ/',
      partOfSpeech: 'verb',
      meaning: 'Làm hài lòng, thỏa mãn',
      example: 'He was gratified by the positive feedback.',
      synonyms: ['please', 'satisfy', 'delight'],
      category: 'General',
    },
    {
      id: '10',
      word: 'Harmony',
      phonetic: '/ˈhɑːməni/',
      partOfSpeech: 'noun',
      meaning: 'Sự hòa hợp, hòa thuận',
      example: 'The team works in perfect harmony.',
      synonyms: ['unity', 'agreement', 'coherence'],
      category: 'General',
    },
    {
      id: '11',
      word: 'Illuminate',
      phonetic: '/ɪˈluːmɪneɪt/',
      partOfSpeech: 'verb',
      meaning: 'Chiếu sáng, làm sáng tỏ',
      example: 'Streetlights illuminate the road at night.',
      synonyms: ['light', 'brighten', 'clarify'],
      category: 'General',
    },
    {
      id: '12',
      word: 'Judicious',
      phonetic: '/dʒuːˈdɪʃəs/',
      partOfSpeech: 'adjective',
      meaning: 'Khôn ngoan, sáng suốt',
      example: 'He made a judicious decision in investing early.',
      synonyms: ['wise', 'sensible', 'prudent'],
      category: 'Business',
    },
    {
      id: '13',
      word: 'Keen',
      phonetic: '/kiːn/',
      partOfSpeech: 'adjective',
      meaning: 'Sắc bén, nhiệt tình',
      example: 'She is keen on improving her English.',
      synonyms: ['eager', 'enthusiastic', 'sharp'],
      category: 'General',
    },
    {
      id: '14',
      word: 'Lucrative',
      phonetic: '/ˈluːkrətɪv/',
      partOfSpeech: 'adjective',
      meaning: 'Sinh lợi, có lợi nhuận',
      example: 'He started a lucrative online business.',
      synonyms: ['profitable', 'gainful', 'rewarding'],
      category: 'Business',
    },
    {
      id: '15',
      word: 'Meticulous',
      phonetic: '/məˈtɪkjələs/',
      partOfSpeech: 'adjective',
      meaning: 'Tỉ mỉ, kỹ càng',
      example: 'She kept meticulous records of every transaction.',
      synonyms: ['precise', 'careful', 'thorough'],
      category: 'General',
    },
    {
      id: '16',
      word: 'Novel',
      phonetic: '/ˈnɒvəl/',
      partOfSpeech: 'adjective',
      meaning: 'Mới lạ, độc đáo',
      example: 'The company introduced a novel marketing strategy.',
      synonyms: ['new', 'original', 'innovative'],
      category: 'Business',
    },
    {
      id: '17',
      word: 'Obsolete',
      phonetic: '/ˈɒbsəliːt/',
      partOfSpeech: 'adjective',
      meaning: 'Lỗi thời, không còn dùng',
      example: 'This technology became obsolete within a year.',
      synonyms: ['outdated', 'old-fashioned', 'antiquated'],
      category: 'Tech',
    },
    {
      id: '18',
      word: 'Pragmatic',
      phonetic: '/præɡˈmætɪk/',
      partOfSpeech: 'adjective',
      meaning: 'Thực dụng, thực tế',
      example: 'He took a pragmatic approach to solving the issue.',
      synonyms: ['practical', 'realistic', 'sensible'],
      category: 'Business',
    },
    {
      id: '19',
      word: 'Resilient',
      phonetic: '/rɪˈzɪliənt/',
      partOfSpeech: 'adjective',
      meaning: 'Kiên cường, hồi phục nhanh',
      example: 'The economy proved resilient after the crisis.',
      synonyms: ['strong', 'tough', 'flexible'],
      category: 'General',
    },
    {
      id: '20',
      word: 'Substantiate',
      phonetic: '/səbˈstænʃieɪt/',
      partOfSpeech: 'verb',
      meaning: 'Chứng minh, xác nhận',
      example: 'You need evidence to substantiate your claim.',
      synonyms: ['prove', 'validate', 'confirm'],
      category: 'Academic',
    },
  ],
};

export const LEARNING_MODES = [
  {
    name: 'Flashcards',
    description: 'Thẻ ghi nhớ',
    icon: BookOpen,
    url: '/flashcards',
    isActive: true,
    customClassName: 'bg-gradient-to-br from-orange-400 to-orange-600',
  },
  {
    name: 'Bài quiz',
    description: 'Kiểm tra kiến thức',
    icon: Zap,
    url: '/quiz',
    isActive: false,
    customClassName: 'bg-gradient-to-br from-blue-400 to-blue-600',
  },
  {
    name: 'Luyện phát âm',
    description: 'Cải thiện kỹ năng nói',
    icon: Volume2,
    url: '/pronunciation',
    isActive: false,
    customClassName: 'bg-gradient-to-br from-purple-400 to-purple-600',
  },
  {
    name: 'trò chơi',
    description: 'Học qua trò chơi',
    icon: Gamepad2,
    url: '/games',
    isActive: false,
    customClassName: 'bg-gradient-to-br from-green-400 to-green-600',
  },
];
